folio-org/edge-inn-reach

Dockerfile
Jenkinsfile

EDGINREACH-4: Create edge-inn-reach folio module
[EDGINREACH-4](https://issues.folio.org/browse/EDGINREACH-4)
Create new Spring based EDGE module and pass it through standard new module creation procedure. 
Number of order transactions have to be greater than 0
Add additional checking of amount of pending encumbrances to avoid transaction creating when there are no encumbrances at all.  …

EDGINREACH-4: Create edge-inn-reach folio module. Small updates.

---

Dockerfile
Jenkinsfile

EDGINREACH-4: Create edge-inn-reach folio module
[EDGINREACH-4](https://issues.folio.org/browse/EDGINREACH-4)
Create new Spring based EDGE module and pass it through standard new module creation procedure. 
Number of order transactions have to be greater than 0
Add additional checking of amount of pending encumbrances to avoid transaction creating when there are no encumbrances at all.  …

EDGINREACH-4: Create edge-inn-reach folio module. Temporary removed dependency on back-end module

---

src/main/java/org/folio/edge/client/InnReachClient.java
src/main/java/org/folio/edge/config/properties/SecurityStoreConfigProperties.java
src/main/java/org/folio/edge/controller/InnReachProxyController.java
src/main/java/org/folio/edge/domain/InnReachRequestBuilder.java
src/main/java/org/folio/edge/domain/dto/InnReachRequest.java
src/main/java/org/folio/edge/security/service/SecurityManagerService.java
src/test/java/org/folio/edge/domain/InnReachRequestBuilderTest.java

Proxy all headers from edge-inn-reach proxy controller to mod-inn-reach controllers.
- Proxy all headers from edge-inn-reach proxy controller to mod-inn-reach controllers.
- Add debug log messages
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …

EDGINREACH-17: Proxy all headers to mod-inn-reach

---

src/main/java/org/folio/edge/config/SecurityConfig.java
src/main/java/org/folio/edge/controller/AuthenticationController.java
src/test/java/org/folio/edge/controller/AuthenticationControllerTest.java

Fix URI to get JWT token
- Change URI
- Update tests
While it's helpful for reviewers to …

EDGINREACH-18: Fix URI to get JWT token

---

pom.xml

Upgrade Log4j2 version to 2.15.0
- Added log4j2.version maven property to override the version
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …

Upgrade Log4j2 version to 2.15.0

---

pom.xml

upgrade spring-boot-starter-parent from 2.3.4.RELEASE to >= 2.6.6 or >= 2.5.12.RELEASE
or upgrade Spring Framework from 5.2.9.RELEASE to 5.2.20.RELEASE
or apply some other effective fix
or explain why edge-inn-reach is not affected by Spring4Shell.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

[EDGINREACH-33] Spring4Shell Lotus/Kiwi (CVE-2022-22965)

---

NEWS.md
pom.xml

Updated the version in pom to 2.0.2-SNAPSHOT

Updated the version in pom to 2.0.2-SNAPSHOT

---

src/main/java/org/folio/edge/authentication/JwtAuthenticationConverter.java
src/main/java/org/folio/edge/client/InnReachRequestInterceptor.java
src/main/java/org/folio/edge/client/OkapiFeignClientProxy.java
src/main/java/org/folio/edge/client/error/FeignErrorDecoder.java
src/main/java/org/folio/edge/config/JwtConfiguration.java
src/main/java/org/folio/edge/config/SecurityConfig.java
src/main/java/org/folio/edge/controller/AuthenticationController.java
src/main/java/org/folio/edge/controller/InnReachProxyController.java
src/main/java/org/folio/edge/controller/exception/ExceptionHandlerController.java
src/main/java/org/folio/edge/domain/InnReachRequestBuilder.java
src/main/java/org/folio/edge/domain/service/impl/AuthenticationServiceImpl.java
src/main/java/org/folio/edge/domain/service/impl/JwtAccessTokenServiceImpl.java
src/main/java/org/folio/edge/filter/ExceptionHandlerFilter.java
src/main/java/org/folio/edge/security/filter/EdgeSecurityFilter.java
src/main/java/org/folio/edge/security/service/SecurityService.java
src/main/java/org/folio/edge/security/store/SecureTenantsProducer.java
src/main/java/org/folio/edge/security/store/TenantAwareAWSParamStore.java
src/main/java/org/folio/edge/utils/CredentialsUtils.java
src/main/java/org/folio/edge/validation/BasicAuthenticationValidator.java

EDGINREACH-30 - https://issues.folio.org/browse/EDGINREACH-30 - Logging improvement.
Logging should be improved for more productive troubleshooting.
As per this page the logging has improvised in this module. -  https://wiki.folio.org/display/DD/Logging

[EDGINREACH-30] - Enhanced the logs.

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Edgeinreach 49/release 2.0.2

---

NEWS.md
pom.xml

[EDGINREACH-50](https://issues.folio.org/browse/EDGINREACH-50)
Release: Orchid - Edge-Inn-Reach
- Are the JIRAs under active development?  
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …

Release PR v3.0.0 (Orchid)

---

NEWS.md
pom.xml

To release EDGINREACH-52 for Orchid Bug Fix
While it's helpful for reviewers to help …

Orchid Bug Fix - 3.0.1

---

pom.xml

The purpose of the PR is to update the folio spring base version to 7.0.0
While it's helpful …

EDGINREACH-56 folio-spring-base version updated to 7.0.0

---

pom.xml

The purpose of this PR is to use edge-common-spring property version for edge-common-spring dependency.
**Evidence**
After the change, the build is successful.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …

EDGINREACH-56

---

README.md

Please see: https://issues.folio.org/browse/EDGINREACH-51

EDGINREACH-51: Cross-Site Request Forgery (CSRF) in SecurityConfig.java

---

pom.xml

Upgrade Spring version for Poppy
Upgrade the versions in pom.xml
While it's helpful for …

[EDGINREACH-61] - Upgrade Spring version for Poppy

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Poppy release
While it's helpful for reviewers to help identify potential problems, ensuring …

EDGINREACH-60 - Poppy Release

---

pom.xml
src/main/resources/application.yml

The purpose of the PR is to implement EDGINREACH-62
While it's helpful for reviewers to help …

EDGINREACH-62 Upgrading dependencies for Quesnelia

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

For Q release.
While it's helpful for reviewers to help identify potential problems, …

Q release 3.2.0

---

NEWS.md

To release 3.2.1

---

pom.xml

[EDGINREACH-66] - Update version in pom

---

NEWS.md
pom.xml

Tmp release 3.2.1

---

pom.xml
src/main/java/org/folio/edge/EdgeInnReachApplication.java

EDGINREACH-67: fixed BC dependency clash

EDGINREACH-67: fixed BC dependency clash

---

NEWS.md
pom.xml
src/main/java/org/folio/edge/EdgeInnReachApplication.java

To release 3.2.3

---

NEWS.md
pom.xml

To release 3.2.4
While it's helpful for reviewers to help identify potential problems, …

To release 3.2.4

---

NEWS.md
pom.xml

To release 3.2.5

---

descriptors/ModuleDescriptor-template.json
pom.xml

EDGINREACH-76 Update pom.xml and interface dependencies for Ramsons

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Ramsons release

---

NEWS.md
pom.xml

To release 3.3.1

---

NEWS.md
pom.xml

Post release 3.3.1

---

pom.xml
src/main/java/org/folio/edge/security/store/TenantAwareAWSParamStore.java

[EDGINREACH-79](https://folio-org.atlassian.net/browse/EDGINREACH-79)

EDGINREACH-79 Sunflower 2025 R1 - Migrate AWS SDK for Java from 1.x to 2.x

---

NEWS.md
pom.xml

Tmp release 3.5.0 for app-inn-reach release

Tmp release 3.5.0

---

NEWS.md
pom.xml

Tmp release v3.4.0

---

pom.xml

https://folio-org.atlassian.net/browse/EDGINREACH-85
Removes bouncy castle from artifact, so it won't conflict with TLS libraries that are set by FSE team
- Exclude `org.bouncycastle:bcprov-jdk18on` from `org.springframework.cloud:spring-cloud-starter-openfeign`
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …

EDGINREACH-85: Fix TLS mode

---

NEWS.md
pom.xml

release changes from [EDGINREACH-85](https://folio-org.atlassian.net/browse/EDGINREACH-85)
- prepare release artifacts
- update NEWS.md
[EDGINREACH-87](https://folio-org.atlassian.net/browse/EDGINREACH-87)

EDGINREACH-87: Release v3.4.1
